title: Digital Belajar - Python
description: Repositori catatan belajar bahasa pemrograman Python
domain: digital-belajar.github.io
url: http://digital-belajar.github.io/python
github_username:  digital-belajar

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme