title: Ruang Belajar - Python
description: Repositori catatan belajar bahasa pemrograman Python
domain: pujangga123.github.io
url: http://ruang-belajar.github.io/python
github_username:  pujangga123

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme